FazTipster/Controllers/BillingPlansController.cs
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FazTipster.Controllers
{
    [Authorize(Roles = "Masteradmin")]
    public class BillingPlansController : Controller
    {
        public ActionResult Index()
        {
            var apiContext = GetApiContext();

            var list = PayPal.Api.Plan.List(apiContext, status: "ACTIVE");

            if (list == null || !list.plans.Any())
            {
                SeedBillingPlans(apiContext);
                list = PayPal.Api.Plan.List(apiContext, status: "ACTIVE");
            }

            return View(list);
        }

        //public ActionResult Delete(string id)
        //{
        //    var apiContext = GetApiContext();

        //    var plan = new Plan()
        //    {
        //        id = id
        //    };

        //    plan.Delete(apiContext);

        //    return RedirectToAction("Index");
        //}

        public ActionResult DeleteAll()
        {
            var apiContext = GetApiContext();

            var list = PayPal.Api.Plan.List(apiContext, status: "ACTIVE");

            foreach (var plan in list.plans)
            {
                var deletePlan = new Plan()
                {
                    id = plan.id
                };

                deletePlan.Delete(apiContext);
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Create the default billing plans for this example website
        /// </summary>
        private void SeedBillingPlans(APIContext apiContext)
        {
            //1. Create Paypal plan objects, using static Paypal class Plan.
            var AndyTipsterMonthlyPackage = new Plan()
            {
                name = "Andy Tipster Package - Monthly Subscription",
                description = "Andy Tipster Package, Monthly Subscription, Specialising in UK Racing.",
                type = "infinite",
                payment_definitions = new List<PaymentDefinition>()
                {
                    new PaymentDefinition()
                    {
                        name = "Regular Payments",
                        type = "REGULAR",
                        frequency = "MONTH",
                        frequency_interval = "1",
                        amount = new Currency()
                        {
                            currency = "GBP",
                            value = "13.00"
                        },
                        cycles = "0"
                    }
                },
                merchant_preferences = new MerchantPreferences()
                {
                    // The initial payment
                    setup_fee = new Currency()
                    {
                        currency = "GBP",
                        value = "13.00"
                    },
                    return_url = Url.Action("Return", "Subscription", null, Request.Url.Scheme),
                    cancel_url = Url.Action("Cancel", "Subscription", null, Request.Url.Scheme)
                }
            };
            var AndyTipster3MonthsPackage = new Plan()
            {
                name = "Andy Tipster Package - Three Months Subscription",
                description = "Andy Tipster Package, Three Months Subscription, Specialising in UK Racing.",
                type = "infinite",
                payment_definitions = new List<PaymentDefinition>()
                {
                    new PaymentDefinition()
                    {
                        name = "Regular Payments",
                        type = "REGULAR",
                        frequency = "MONTH",
                        frequency_interval = "3",
                        amount = new Currency()
                        {
                            currency = "GBP",
                            value = "35.00"
                        },
                        cycles = "0"
                    }
                },
                merchant_preferences = new MerchantPreferences()
                {
                    // The initial payment
                    setup_fee = new Currency()
                    {
                        currency = "GBP",
                        value = "35.00"
                    },
                    return_url = Url.Action("Return", "Subscription", null, Request.Url.Scheme),
                    cancel_url = Url.Action("Cancel", "Subscription", null, Request.Url.Scheme)
                }
            };

            var IrishHorseRacingMonthlyPackage = new Plan()
            {
                name = "Irish Horse Racing - Monthly Subscription",
                description = "Irish Horse Racing, Monthly Subscription, Solely Irish Horse Racing Tips",
                type = "infinite",
                payment_definitions = new List<PaymentDefinition>()
                {
                    new PaymentDefinition()
                    {
                        name = "Regular Payments",
                        type = "REGULAR",
                        frequency = "MONTH",
                        frequency_interval = "1",
                        amount = new Currency()
                        {
                            currency = "GBP",
                            value = "10.00"
                        },
                        cycles = "0"
                    }
                },
                merchant_preferences = new MerchantPreferences()
                {
                    // The initial payment
                    setup_fee = new Currency()
                    {
                        currency = "GBP",
                        value = "10.00"
                    },
                    return_url = Url.Action("Return", "Subscription", null, Request.Url.Scheme),
                    cancel_url = Url.Action("Cancel", "Subscription", null, Request.Url.Scheme)
                }
            };
            var IrishHorseRacing3MonthsPackage = new Plan()
            {
                name = "Irish Horse Racing - Three Months Subscription",
                description = "Irish Horse Racing, Three Months Subscription, Solely Irish Horse Racing Tips",
                type = "infinite",
                payment_definitions = new List<PaymentDefinition>()
                {
                    new PaymentDefinition()
                    {
                        name = "Regular Payments",
                        type = "REGULAR",
                        frequency = "MONTH",
                        frequency_interval = "3",
                        amount = new Currency()
                        {
                            currency = "GBP",
                            value = "27.50"
                        },
                        cycles = "0"
                    }
                },
                merchant_preferences = new MerchantPreferences()
                {
                    // The initial payment
                    setup_fee = new Currency()
                    {
                        currency = "GBP",
                        value = "27.50"
                    },
                    return_url = Url.Action("Return", "Subscription", null, Request.Url.Scheme),
                    cancel_url = Url.Action("Cancel", "Subscription", null, Request.Url.Scheme)
                }
            };

            var UltimatepackMonthlyPackage = new Plan()
            {
                name = "Ultimate pack - Monthly Subscription",
                description = "Ultimate pack, Enjoy The 2 Brands For Less, The ultimate pack for the ultimate Deal",
                type = "infinite",
                payment_definitions = new List<PaymentDefinition>()
                {
                    new PaymentDefinition()
                    {
                        name = "Regular Payments",
                        type = "REGULAR",
                        frequency = "MONTH",
                        frequency_interval = "1",
                        amount = new Currency()
                        {
                            currency = "GBP",
                            value = "17.00"
                        },
                        cycles = "0"
                    }
                },
                merchant_preferences = new MerchantPreferences()
                {
                    // The initial payment
                    setup_fee = new Currency()
                    {
                        currency = "GBP",
                        value = "17.00"
                    },
                    return_url = Url.Action("Return", "Subscription", null, Request.Url.Scheme),
                    cancel_url = Url.Action("Cancel", "Subscription", null, Request.Url.Scheme)
                }
            };
            var Ultimatepack3MonthPackage = new Plan()
            {
                name = "Ultimate pack - Three Months Subscription",
                description = "Ultimate pack, Enjoy The 2 Brands For Less, The ultimate pack for the ultimate Deal",
                type = "infinite",
                payment_definitions = new List<PaymentDefinition>()
                {
                    new PaymentDefinition()
                    {
                        name = "Regular Payments",
                        type = "REGULAR",
                        frequency = "MONTH",
                        frequency_interval = "3",
                        amount = new Currency()
                        {
                            currency = "GBP",
                            value = "45.00"
                        },
                        cycles = "0"
                    }
                },
                merchant_preferences = new MerchantPreferences()
                {
                    // The initial payment
                    setup_fee = new Currency()
                    {
                        currency = "GBP",
                        value = "45.00"

FazTipster/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FazTipster.Entities;
using FazTipster.Models;

namespace FazTipster.Controllers
{
    [Authorize(Roles = "Masteradmin")]
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Questions
        public ActionResult Index()
        {
            return View(db.Questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = db.Questions.Find(id);
            if (questions == null)
            {
                return HttpNotFound();
            }
            return View(questions);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Question,Answer")] Questions questions)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(questions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(questions);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = db.Questions.Find(id);
            if (questions == null)
            {
                return HttpNotFound();
            }
            return View(questions);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Question,Answer")] Questions questions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(questions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(questions);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Questions questions = db.Questions.Find(id);
            if (questions == null)
            {
                return HttpNotFound();
            }
            return View(questions);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Questions questions = db.Questions.Find(id);
            db.Questions.Remove(questions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FazTipster/Views/Shared/_ExistingSubscription.cshtml
@model FazTipster.Models.Subscription.ExistingSubscriptionVM

    @{
        ViewBag.Title = "Existing Subscription Found";
    }


    <div class="heads">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>You seem to already have a subscription.</h1>
                    @*<h3>All our payments are through Paypal. You can use your Paypal account or a Debit Card on the next step.</h3>
                    <h3>Please check your selected subscription and click payment button.</>*@
                </div>
            </div>
        </div>
    </div>


    <div class="row" style="margin-top:50px;">
        <div class="col-md-6 col-sm-8">
            <div class="pricign-box animated fadeInUp animation-delay-7">
                <div class="pricing-box-header">
                    <h2>@Model.PlanName</h2>
                    @*<p>nisi anim mollit in labore ut esse</p>*@
                </div>
                
                <div class="pricing-box-content">
                    <ul>
                        <li>Paypal Ref:  @Model.PaypalAgreement</li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

FazTipster/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Andy Tipster</title>
    <meta name="description" content="Andy Tipster - The Number One in Sports Tips, Make The Most out of Your Bets.">
    <meta name="keywords" content="  Sports Betting, Horse Racing, Gambling, Tipster, Profit, Winners, Andy Tipster">
    <meta name="author" content="agilecoding.com">

    <!-- Custom styles for this template -->
    <link href="~/Content/Template/css/style.css" rel="stylesheet">


    <link href="~/Content/Template/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/Template/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/Template/css/animate.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/Template/css/lightbox.css" rel="stylesheet" media="screen">
    <link href="~/Content/Template/css/syntax/shCore.css" rel="stylesheet" media="screen">
    <link href="~/Content/Template/css/syntax/shThemeDefault.css" rel="stylesheet" media="screen">

    <link href="~/Content/Template/css/style.css" rel="stylesheet" media="screen">
    <link href="~/Content/Template/css/color-default.css" rel="stylesheet" media="screen" title="default">
    <link href="~/Content/Template/css/width-full.css" rel="stylesheet" media="screen" title="default">

    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
</head>


<body>

    @*Facebook login scripts*@
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '{your-app-id}',
                cookie: true,
                xfbml: true,
                version: 'v4.0'
            });

            FB.AppEvents.logPageView();

        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    @*End of Facebook login scripts*@

    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '910702312285636',
                xfbml: true,
                version: 'v2.5'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="boxed animated fadeIn animation-delay-5">

        <header id="header" class="hidden-xs">
            <div class="container">
                <div id="header-title">
                    <!--<h1 class="animated fadeInDown"><a href="../index.html">Andy<span>tipster</span></a></h1>-->
                    <h1 class="animated ">
                        <a href="@Url.Action("Index", "Home")">Andy<span>tipster</span></a>
                    </h1>
                    <p class="animated fadeInLeft">The Number One in Sports Tips, Make The Most out of Your Bets.</p>
                </div>
            </div> <!-- container -->
        </header> <!-- header -->

        <nav class="navbar navbar-static-top navbar-mind" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand visible-xs" href="@Url.Action("Index", "Home")">Andy<span>tipster</span></a>

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-mind-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-bars fa-inverse"></i>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-mind-collapse" id="bs-example-navbar-collapse-1">


                    <ul class="nav navbar-nav nav-left">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li class="btn btn-success">@Html.ActionLink("Subscriptions", "Index", "Subscription")</li>
                        <li>@Html.ActionLink("FAQ", "Faq", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tips<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("AndyTipster Tips", "AndyTipsterTips", "Home")</li>
                                    <li>@Html.ActionLink("Irish Racing Tips", "IrishRacingTips", "Home")</li>
                                    <li>@Html.ActionLink("Ultimate Pack Tips", "UltimatePackTips", "Home")</li>
                                </ul>
                            </li>
                        }


                        @if (User.Identity.IsAuthenticated && User.IsInRole("Masteradmin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Billing Plans", "Index", "BillingPlans")</li>
                                    <li>@Html.ActionLink("Subscribers", "Index", "Subscribers")</li>
                                    <li>@Html.ActionLink("Edit Home", "Edit", "LandingPages")</li>
                                    <li>@Html.ActionLink("Edit About", "Edit", new { controller = "Abouts", id = 1 })</li>
                                    <li>@Html.ActionLink("Edit FAQ", "Index", "Questions")</li>
                                    <li>@Html.ActionLink("Edit Tips", "Edit", new { controller = "Tips", id = 1 })</li>
                                    <li>@Html.ActionLink("Download Emails", "EmailList", "Home")</li>

                                </ul>
                            </li>
                        }

                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li> @Html.Partial("_LoginPartial")</li>
                    </ul>

                </div><!-- navbar-collapse -->
            </div> <!-- container -->
        </nav> <!-- navbar navbar-default -->



        <div>


            <!-- InstanceBeginEditable name="contents" -->
            <br />
            <div class="container body-content">
                @RenderBody()
            </div>

            <footer id="footer" style="margin-top:50px;">

                <p>&copy; 2016 <a href="#">www.andytipster.com</a>, inc. All rights reserved.</p>
                <p>Designed and Maintained By <a href="http://www.agilecoding.com/">agilecoding.com: Simple but Smart</a>.</p>
            </footer>

        </div> <!-- boxed -->

    </div>
    <!-- Scripts -->
    <script src="~/Content/Template/js/jquery-1.10.2.min.js"></script>
    <script src="~/Content/Template/js/jquery.cookie.js"></script>
    <script src="~/Content/Template/js/bootstrap.min.js"></script>
    <script src="~/Content/Template/js/jquery.mixitup.min.js"></script>
    <script src="~/Content/Template/js/lightbox-2.6.min.js"></script>
    <script src="~/Content/Template/js/holder.js"></script>
    <script src="~/Content/Template/js/app.js"></script>
    <script src="~/Content/Template/js/styleswitcher.js"></script>

    <script src="~/Content/Template/js/syntax/shCore.js"></script>
    <script src="~/Content/Template/js/syntax/shBrushXml.js"></script>
    <script src="~/Content/Template/js/syntax/shBrushJScript.js"></script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>

</html>