FazTipster/Entities/About.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FazTipster.Entities
{
    public class About
    {
        public int Id { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [DisplayName("Page heading")]
        public string Header { get; set; }

        [Required]
        [StringLength(2000, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [DisplayName("First top paragraph")]
        public string FirstTopParagraph { get; set; }

        [Required]
        [StringLength(2000, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [DisplayName("Second top paragraph")]
        public string SecondTopParagraph { get; set; }

        [DisplayName("A title to describe your packages")]
        public string PackagesTitle { get; set; }

        [DisplayName("Package one heading")]
        public string PackageOneHeading { get; set; }

        [Required]
        [StringLength(2000, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [DisplayName("Package one details")]
        public string PackageOneDetails { get; set; }

        [DisplayName("Package two heading")]
        public string PackageTwoHeading { get; set; }

        [Required]
        [StringLength(2000, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [DisplayName("Package two details")]
        public string PackageTWoDetails { get; set; }

        [DisplayName("Package three heading")]
        public string PackageThreeHeading { get; set; }
        
        [Required]
        [StringLength(2000, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [DisplayName("Package three details")]
        public string PackageThreeDetails { get; set; }


    }
}

FazTipster/Models/Faq/IndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FazTipster.Entities;

namespace FazTipster.Models.Faq
{
    public class IndexVM
    {
        public List<Questions> Questions { get; set; } = new List<Questions>();
    }
}

FazTipster/ViewModels/EmailListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FazTipster.ViewModels
{
    public class EmailListViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

FazTipster/Controllers/AboutsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FazTipster.Entities;
using FazTipster.Models;

namespace FazTipster.Controllers
{
    [Authorize(Roles = "Masteradmin")]
    public class AboutsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        //public ActionResult Index()
        //{
        //    return View(db.Abouts.ToList());
        //}

       
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    About about = db.Abouts.Find(id);
        //    if (about == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(about);
        //}

       
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Abouts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Header,FirstTopParagraph,SecondTopParagraph,PackagesTitle,PackageOneHeading,PackageOneDetails,PackageTwoHeading,PackageTWoDetails,PackageThreeHeading,PackageThreeDetails")] About about)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Abouts.Add(about);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(about);
        //}

      
        public ActionResult Edit(int? id)
        {
            About about = null;

            if (id == null)
            {
                about = db.Abouts.FirstOrDefault();
            }
            else
            {
                about = db.Abouts.Find(id);

                if (about == null)
                {
                    about = db.Abouts.FirstOrDefault();
                }
            }
        
            return View(about);
        }

        // POST: Abouts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Header,FirstTopParagraph,SecondTopParagraph,PackagesTitle,PackageOneHeading,PackageOneDetails,PackageTwoHeading,PackageTWoDetails,PackageThreeHeading,PackageThreeDetails")] About about)
        {
            if (ModelState.IsValid)
            {
                db.Entry(about).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(about);
            
        }

     
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    About about = db.Abouts.Find(id);
        //    if (about == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(about);
        //}

       
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    About about = db.Abouts.Find(id);
        //    db.Abouts.Remove(about);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FazTipster/Controllers/SubscriptionController.cs
using FazTipster.Entities;
using FazTipster.Models;
using FazTipster.Models.Subscription;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FazTipster.Controllers
{
    [Authorize]
    public class SubscriptionController : Controller
    {

        private Models.ApplicationDbContext _dbContext => HttpContext.GetOwinContext().Get<ApplicationDbContext>();
        public ActionResult Index()
        {
            var model = new IndexVm()
            {
                Plans = Models.Subscription.Plan.Plans
            };

            return View(model);
        }

        public ActionResult Purchase(string id)
        {

            var currentUserId = User.Identity.GetUserId();
            var currentUser = _dbContext.Users.Where(x => x.Id == currentUserId).FirstOrDefault();

            if (currentUser.SubscriptionId != null)
            {
                if (currentUser.SubscriptionState.ToLower() == "active" || currentUser.SubscriptionState.ToLower() == "pending")
                {

                    var existingSubscription = new ExistingSubscriptionVM
                    {
                        //Plan = Models.Subscription.Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == id),
                        FirstName = currentUser.FirstName,
                        LastName = currentUser.LastName,
                        Email = currentUser.Email,
                        PlanName = currentUser.SubscriptionDescription,
                        PaypalAgreement = currentUser.PayPalAgreementId
                    };

                    return View("_ExistingSubscription", existingSubscription);

                    ////check which subscription current user has
                    //if (currentUser.SubscriptionDescription == "AndyTipster Monthly Package")
                    //{
                    //    //user has Andy Tipster regular package
                    //    return View("_ExistingSubscription", existingSubscription);

                    //}
                    //else if (currentUser.SubscriptionDescription == "AndyTipster Three Months Package")
                    //{
                    //    //user has Andy Tipster 3 months package
                    //}
                    //else if (currentUser.SubscriptionDescription == "Irish Horse Racing - Monthly Subscription")
                    //{
                    //    //user has Irish Racing regular package
                    //}
                    //else if (currentUser.SubscriptionDescription == "Irish Horse Racing - Three Months Subscription")
                    //{
                    //    //user has Irish 3 months package
                    //}
                    //else if (currentUser.SubscriptionDescription == "Ultimate pack - Monthly Subscription")
                    //{
                    //    //user has Ultimate regular package
                    //}
                    //else if (currentUser.SubscriptionDescription == "Ultimate pack - Three Months Subscription")
                    //{
                    //    //user has Ultimate 3 months package
                    //}
                }
            }
            var model = new PurchaseVm()
            {
                Plan = Models.Subscription.Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == id),
                FirstName = currentUser.FirstName,
                LastName = currentUser.LastName,
                Email = currentUser.Email
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Purchase(PurchaseVm model)
        {
           
            var plan = Models.Subscription.Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == model.Plan.PayPalPlanId);


            if (ModelState.IsValid)
            {
                // Since we take an Initial Payment (instant payment), the start date of the recurring payments will be next month.
                var startDate = DateTime.UtcNow.AddMonths(1);

                var apiContext = GetApiContext();

                var subscription = new Subscription()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    StartDate = startDate,
                    PayPalPlanId = plan.PayPalPlanId
                };
                _dbContext.Subscriptions.Add(subscription);
                _dbContext.SaveChanges();

                var agreement = new Agreement()
                {
                    name = plan.Name,
                    description = plan.Description,
                    start_date = startDate.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                    plan = new PayPal.Api.Plan()
                    {
                        id = plan.PayPalPlanId
                    },
                    payer = new Payer()
                    {
                        payment_method = "paypal"
                    }
                };

                // Send the agreement to PayPal
                var createdAgreement = agreement.Create(apiContext);

                // Save the token so we can match the returned request to our subscription.
                subscription.PayPalAgreementToken = createdAgreement.token;
                subscription.PayPalPlanName = createdAgreement.name;

                _dbContext.SaveChanges();

                // Find the Approval URL to send our user to
                var approvalUrl =
                    createdAgreement.links.FirstOrDefault(
                        x => x.rel.Equals("approval_url", StringComparison.OrdinalIgnoreCase));

                // Send the user to PayPal to approve the payment
                return Redirect(approvalUrl.href);
            }

            model.Plan = plan;
            return View(model);
        }

        public ActionResult Return(string token)
        {
            var subscription = _dbContext.Subscriptions.FirstOrDefault(x => x.PayPalAgreementToken == token);

            var apiContext = GetApiContext();

            var agreement = new Agreement()
            {
                token = token
            };

            var executedAgreement = agreement.Execute(apiContext);

            // Save the PayPal agreement in our subscription so we can look it up later.
            subscription.PayPalAgreementId = executedAgreement.id;
            subscription.PayPalPaymentEmail = executedAgreement.payer.payer_info.email;

            //update currently login user to add Paypal Subscription information.

            var currentUserId = User.Identity.GetUserId();
            var currentUser = _dbContext.Users.Where(x => x.Id == currentUserId).FirstOrDefault();
            currentUser.SubscriptionId = executedAgreement.id;
            currentUser.SubscriptionState = executedAgreement.state;
            currentUser.SubscriptionFirstName = executedAgreement.payer.payer_info.first_name;
            currentUser.SubscriptionLastName = executedAgreement.payer.payer_info.last_name;
            currentUser.SubscriptionEmail = executedAgreement.payer.payer_info.email;
            currentUser.SubscriptionDescription = subscription.PayPalPlanName;
            currentUser.PayPalAgreementId = subscription.PayPalAgreementId;

            //user might not have a postal address.
            //currentUser.SubscriptionPostalCode = executedAgreement.payer.payer_info.billing_address.postal_code;

            _dbContext.SaveChanges();

            return RedirectToAction("Thankyou");
        }

        public ActionResult Cancel()
        {
            return View();
        }

        public ActionResult ThankYou()
        {
            return View();
        }

        private APIContext GetApiContext()
        {
            // Authenticate with PayPal
            var config = ConfigManager.Instance.GetProperties();
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);
            return apiContext;
        }
    }
}

FazTipster/Views/Home/About.cshtml
@model FazTipster.Entities.About

@{
    ViewBag.Title = "About";
}

@if (Model != null)
{ 
    <div class="row">
        <div class="col-xs-12">
            <p class="lead lead-lg text-center animated bounceInLeft animation-delay-12"><strong>@Model.Header</strong></p>
        </div>

        <div class="col-md-12">
            <section class="animated fadeInDown animation-delay-8">
                @*<h2 class="section-title">@Model.Header</h2>*@

                <p class="p-lg">

                    @Model.FirstTopParagraph  <br />
                    @Model.SecondTopParagraph <br />


            </section>
            <section class="animated fadeIn animation-delay-10">
                <h3 class="section-title">@Model.PackagesTitle</h3>
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    @Model.PackageOneHeading
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                            <div class="panel-body">
                                @Model.PackageOneDetails
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="collapsed">
                                    @Model.PackageTwoHeading
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse">
                            <div class="panel-body">
                                @Model.PackageTWoDetails
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" class="collapsed">
                                    @Model.PackageThreeHeading
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse">
                            <div class="panel-body">
                                @Model.PackageThreeDetails
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>

    </div>
}
else
{
    <h2>There is no information to display on this page.</h2>
}

FazTipster/Views/Home/Index - Copy.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="row">
    <div class="jumbotron">
        <h1>Welcome to AndyTipster</h1>
        <p class="lead">Your one stop for Winning tips.</p>
        <p><a href="@Url.Action("HowToSubscribe", "Home")" class="btn btn-primary btn-lg">Subscribe in easy steps</a></p>
    </div>
</div>*@

@*<div class="container">
        <div class="col-md-6 col-sm-6">



            <div class="AW-Form-452195183"></div>
            <script type="text/javascript">
                            (function (d, s, id) {
                                var js, fjs = d.getElementsByTagName(s)[0];
                                if (d.getElementById(id)) return;
                                js = d.createElement(s); js.id = id;
                                js.src = "//forms.aweber.com/form/83/452195183.js";
                                fjs.parentNode.insertBefore(js, fjs);
                            }(document, "script", "aweber-wjs-d93otjwlr"));
            </script>

            <br />
        </div>

        <div class="col-md-6 col-sm-6">
            <a class="btn btn-primary btn-lg" href="winners.html" role="button">Recent winners</a>
            <a class="btn btn-primary btn-lg" href="https://docs.google.com/spreadsheets/d/1LNXHFH6wEN4BHbb4jiFjzRAfZzeBHhH3I2ueORi8dxc/edit?pref=2&amp;pli=1#gid=0" role="button">Daily Results</a>

            <br />
        </div>

    </div>*@

<div class="container">

    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="pricign-box animated fadeInUp animation-delay-8">
                        <div class="pricing-box-header">
                            <h2>Ultimate pack</h2>
                            <p>Enjoy The 2 Brands For Less, The ultimate pack for the ultimate Deal</p>
                        </div>
                        @*<img src="~/Content/Template/img/uk-sports-home-image.jpg" class="img-responsive" alt="Image">*@
                    <div class="pricing-box-price">
                        <a href="@Url.Action("Purchase", "Subscription", new { id = "P-8AC488780J6779351TE4KW7A" })">
                            <h3>&pound;17 <sub>/ month</sub></h3>
                        </a> 


                    </div>
                    <div class="pricing-box-price">
                        <a href="@Url.Action("Purchase", "Subscription", new {id =  "P-9H0036907S152411BTE4K53Q"})">
                            <h3>&pound;45 <sub>/ 3 months</sub> </h3>
                            </a>
                    </div>
                        <div class="pricing-box-content">
                            <ul>
                                <li><i class="fa fa-check"></i>The combination of all sports- Horse Racing from the UK and IRE aswell as other sports</li>
                                <li><i class="fa fa-check"></i>Upon joining get our Guide and join our Ever growing Community</li>
                                <li><i class="fa fa-check"></i>Payments made by secure paypal</li>
                                <li><i class="fa fa-check"></i>Want to Pay by bank transfer, contact us</li>
                            </ul>
                        </div>
                        @*<div class="pricing-box-footer">
                                <div class="row">
                                    <div class="col-md-6 col-sm-6">
                                        Monthly Subscription
                                    </div>
                                    <div class="col-md-6 col-sm-6"> 3 Monthly Subscription </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-6">
                                        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                            <input type="hidden" name="cmd" value="_s-xclick">
                                            <input type="hidden" name="hosted_button_id" value="KHGW63NN8XESG">
                                            <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
                                            <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                        </form>
                                    </div>
                                    <div class="col-md-6 col-sm-6">
                                        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                            <input type="hidden" name="cmd" value="_s-xclick">
                                            <input type="hidden" name="hosted_button_id" value="RVBUN6L6JT9LE">
                                            <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
                                            <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                        </form>
                                    </div>
                                </div>
                            </div>*@
                    </div>
                </div>


            </div> <!-- row -->
        </div>

    </div>
    <div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="pricign-box animated fadeInUp animation-delay-7">
                <div class="pricing-box-header">
                    <h2>Andy Tipster Package</h2>
                    <p>Specialising in UK Racing</p>
                </div>
                <img src="~/Content/Template/img/uk-sports-home-image.jpg" class="img-responsive" alt="Image">
                <div class="pricing-box-price">
                    <a href="@Url.Action("Purchase", "Subscription", new {id =  "P-8FA01768GN086944DTE4J2PI"})">
                        <h3>&pound;13 <sub>/ month</sub></h3>
                        </a>
                </div>
                <div class="pricing-box-price">
                    <a href="@Url.Action("Purchase", "Subscription", new {id =  "P-8NM2876475709704TTE4KBHA"})">
                        <h3>  &pound;35 <sub>/ 3 months</sub> </h3>
                        </a>
                </div>

                <div class="pricing-box-content">
                    <ul>
                        <li><i class="fa fa-check"></i>Membership group that's amassed Thousands of &pound;&pound; Profit Since Feb 2013</li>
                        <li><i class="fa fa-check"></i>Daily Emails With Hours to get The bets on, No last Minute bets</li>
                        <li><i class="fa fa-check"></i>A Long Term Winning Points System in place as Proven</li>
                        <li><i class="fa fa-check"></i>Join Our Andy Tipster Community and be part of something much bigger</li>
                        <li><i class="fa fa-check"></i>Payments made by secure paypal</li>
                        <li><i class="fa fa-check"></i>Want to Pay by bank transfer, contact us</li>
                    </ul>


                </div>
                @*<div class="pricing-box-footer">
                        <div class="row">
                            <div class="col-md-6 col-sm-6"> Monthly Subscription  </div>
                            <div class="col-md-6 col-sm-6"> 3 Monthly Subscription </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-6">
                                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                    <input type="hidden" name="cmd" value="_s-xclick">
                                    <input type="hidden" name="hosted_button_id" value="HKEPESP58WVUY">
                                    <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
                                    <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                </form>
                            </div>
                            <div class="col-md-6 col-sm-6">
                                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                    <input type="hidden" name="cmd" value="_s-xclick">
                                    <input type="hidden" name="hosted_button_id" value="2PMZJWNZQ7VH8">
                                    <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
                                    <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                </form>
                            </div>



                        </div>
                    </div>*@
            </div>
        </div>


        <div class="col-md-6 col-sm-6">
            <div class="pricign-box pricign-box-pro animated fadeInUp animation-delay-9">
                <div class="pricing-box-header">
                    <h2>Irish Horse Racing</h2>
                    <p>Solely Irish Horse Racing Tips</p>
                </div>
                <img src="~/Content/Template/img/Irish-horce-racing-home-image.jpg" class="img-responsive" alt="Image">
                <div class="pricing-box-price">
                    <a href="@Url.Action("Purchase", "Subscription", new {id =  "P-49A56000A6163212YTE4KIQI"})">
                        <h3>&pound;10 <sub>/ month</sub> </h3>
                        </a>
                </div>
                <div class="pricing-box-price">
                    <a href="@Url.Action("Purchase", "Subscription", new {id =  "P-5U268280XB476211XTE4KPTY"})">
                        <h3>&pound;27.50 <sub>/ 3 months</sub> </h3>
                        </a>
                </div>
                <div class="pricing-box-content">
                    <ul>
                        <li><i class="fa fa-check"></i>A Points System To Ensure a Control and guidance on Winning</li>
                        <li><i class="fa fa-check"></i>Proven Success on facebook With Years of Gains at level Stakes</li>
                        <li><i class="fa fa-check"></i>A Long Term Winning Points System in place as Proven</li>
                        <li><i class="fa fa-check"></i>The Sister But Definitely Not the understudy To Andy Tipster since Dec 2013</li>
                        <li><i class="fa fa-check"></i>Payments made by secure paypal</li>
                        <li><i class="fa fa-check"></i>Want to Pay by bank transfer, contact us</li>
                    </ul>
                </div>
                @*<div class="pricing-box-footer">
                        <div class="row">
                            <div class="col-md-6 col-sm-6"> Monthly Subscription  </div>
                            <div class="col-md-6 col-sm-6"> 3 Monthly Subscription </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-6">
                                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                    <input type="hidden" name="cmd" value="_s-xclick">
                                    <input type="hidden" name="hosted_button_id" value="3UN6CZCU5J8NE">
                                    <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
                                    <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                </form>
                            </div>
                            <div class="col-md-6 col-sm-6">
                                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                    <input type="hidden" name="cmd" value="_s-xclick">
                                    <input type="hidden" name="hosted_button_id" value="KDKN6JPEALU3U">
                                    <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
                                    <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                </form>
                            </div>



                        </div>
                    </div>*@
            </div>
        </div>
    </div>






</div>