FazTipster/Controllers/SubscribersController.cs
using Microsoft.AspNet.Identity.Owin;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FazTipster.Models.Subscription;
using PagedList;

namespace FazTipster.Controllers
{
    [Authorize(Roles = "Masteradmin")]
    public class SubscribersController : Controller
    {
        private Models.ApplicationDbContext _dbContext => HttpContext.GetOwinContext().Get<Models.ApplicationDbContext>();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "CreatedDate" : "";
           

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var subscriptions = _dbContext.Subscriptions.ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                subscriptions = subscriptions.Where(s => s.LastName.Contains(searchString) ||
                                                         s.FirstName.Contains(searchString) ||
                                                         s.Email.Contains(searchString) ||
                                                          s.PayPalPaymentEmail.Contains(searchString) ||
                                                           s.PayPalPlanName.Contains(searchString)
                                                         ).ToList();
            }
            switch (sortOrder)
            {
                case "Email":
                    subscriptions = subscriptions.OrderByDescending(s => s.Email).ToList();
                    break;
                case "PayPalEmail":
                    subscriptions = subscriptions.OrderByDescending(s => s.PayPalPaymentEmail).ToList();
                    break;
                case "FirstName":
                    subscriptions = subscriptions.OrderByDescending(s => s.FirstName).ToList();
                    break;
                case "LastName":
                    subscriptions = subscriptions.OrderByDescending(s => s.LastName).ToList();
                    break;
                case "CreatedDate":
                    subscriptions = subscriptions.OrderByDescending(s => s.StartDate).ToList();
                    break;
                case "Plan":
                    subscriptions = subscriptions.OrderByDescending(s => s.PayPalPlanName).ToList();
                    break;
                default:  // Name ascending 
                    subscriptions = subscriptions.OrderByDescending(s => s.StartDate).ToList();
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(subscriptions.ToPagedList(pageNumber, pageSize));


            //var subscriptions = _dbContext.Subscriptions.OrderByDescending(x => x.StartDate).Take(50).ToList();
            //return View(subscriptions);
        }

        public ActionResult Details(string id)
        {
            var apiContext = GetApiContext();

            var agreement = Agreement.Get(apiContext, id);

            return View(agreement);
        }

        public ActionResult Suspend(string id)
        {
            var apiContext = GetApiContext();

            Agreement.Suspend(apiContext, id, new AgreementStateDescriptor()
            {
                note = "Suspended"
            });

            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult Reactivate(string id)
        {
            var apiContext = GetApiContext();

            Agreement.ReActivate(apiContext, id, new AgreementStateDescriptor()
            {
                note = "Reactivated"
            });

            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult Cancel(string id)
        {
            var apiContext = GetApiContext();

            Agreement.Cancel(apiContext, id, new AgreementStateDescriptor()
            {
                note = "Cancelled"
            });

            return RedirectToAction("Details", new { id = id });
        }



        private APIContext GetApiContext()
        {
            // Authenticate with PayPal
            var config = ConfigManager.Instance.GetProperties();
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);
            return apiContext;
        }
    }
}

FazTipster/Views/Subscribers/Details.cshtml
@using Newtonsoft.Json
@model PayPal.Api.Agreement

@{
    ViewBag.Title = "Subscription Details";
}

<div class="heads" style="background: url(/public/img/brewery-back1.jpg) 50% 27%;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2><span>//</span> Subscription Details</h2>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container">
        <div class="row confirm">
            <div class="col-md-12">
                <a href="@Url.Action("Suspend", "Subscribers", new {id=Model.id})" @(Model.state != "Active" ? "disabled" : "") class="btn btn-warning">Suspend</a>
                <a href="@Url.Action("Reactivate", "Subscribers", new {id=Model.id})" @(Model.state != "Suspended" ? "disabled" : "") class="btn btn-warning">Re-activate</a>
                <a href="@Url.Action("Cancel", "Subscribers", new {id=Model.id})" @(Model.state != "Cancelled" ? "" : "disabled") class="btn btn-warning">Cancel</a>
            </div>
        </div>
        <div class="row confirm">
            <div class="col-md-12">
                <pre>@JsonConvert.SerializeObject(Model, Formatting.Indented)</pre>
            </div>
        </div>
    </div>
</div>

FazTipster/Views/Subscribers/Index.cshtml
@*@using FazTipster.Models.Subscription
    @model List<FazTipster.Entities.Subscription>*@


@using FazTipster.Models.Subscription
@model PagedList.IPagedList<FazTipster.Entities.Subscription>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Subscribers";
}

@*<div class="heads" style="background: url(/public/img/brewery-back1.jpg) 50% 27%;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2><span>//</span> Subscribers</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="page-content">
        <div class="container">
            <div class="row confirm">
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Email</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Paypal Email</th>
                                <th>PayPal Agreement</th>
                                <th>Created Date</th>
                                <th>Plan</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                if ((Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == item.PayPalPlanId)?.Name ?? "[Deleted Plan]") != "[Deleted Plan]")
                                {
                                    <tr>
                                        <td>@item.Email</td>
                                        <td>@item.FirstName</td>
                                        <td>@item.LastName</td>
                                        <td>@item.PayPalPaymentEmail</td>
                                        <td>@item.PayPalAgreementId</td>
                                        <td>@item.StartDate</td>
                                        <td>@(Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == item.PayPalPlanId)?.Name ?? "[Deleted Plan]")</td>
                                        <td class="text-right">
                                            <a href="@Url.Action("Details", "Subscribers" ,new {id=item.PayPalAgreementId})">View Details</a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>*@


@using (Html.BeginForm("Index", "Subscribers", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th> @Html.ActionLink("Start Date", "Index", new { sortOrder = "StartDate", currentFilter = ViewBag.CurrentFilter })</th>
        <th> @Html.ActionLink("Email", "Index", new { sortOrder = "Email", currentFilter = ViewBag.CurrentFilter })</th>
        <th> @Html.ActionLink("First Name", "Index", new { sortOrder = "FirstName", currentFilter = ViewBag.CurrentFilter })</th>
        <th> @Html.ActionLink("Last Name", "Index", new { sortOrder = "LastName", currentFilter = ViewBag.CurrentFilter })</th>
        <th> @Html.ActionLink("Paypal Email", "Index", new { sortOrder = "PayPalPaymentEmail", currentFilter = ViewBag.CurrentFilter })</th>
        <th>PayPal Agreement</th>
        <th>Plan</th>
        <th> @Html.ActionLink("Plan", "Index", new { sortOrder = "PayPalPlanName", currentFilter = ViewBag.CurrentFilter })</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>@item.StartDate</td>
            <td>@item.Email</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.PayPalPaymentEmail</td>
            <td>@item.PayPalAgreementId</td>

            <td>@(Plan.Plans.FirstOrDefault(x => x.PayPalPlanId == item.PayPalPlanId)?.Name ?? "[Deleted Plan]")</td>
            <td class="text-right">
                <a href="@Url.Action("Details", "Subscribers" ,new {id=item.PayPalAgreementId})">View Details</a>
            </td>
        </tr>

    }


    @*case "Email":
        subscriptions = subscriptions.OrderByDescending(s => s.Email);
        break;
        case "PayPalEmail":
        subscriptions = subscriptions.OrderByDescending(s => s.PayPalPaymentEmail);
        break;
        case "FirstName":
        subscriptions = subscriptions.OrderByDescending(s => s.FirstName);
        break;
        case "LastName":
        subscriptions = subscriptions.OrderByDescending(s => s.LastName);
        break;
        case "CreatedDate":
        subscriptions = subscriptions.OrderByDescending(s => s.StartDate);
        break;
        case "Plan":
        subscriptions = subscriptions.OrderByDescending(s => s.PayPalPlanName);
        break;
        default:  // Name ascending
        subscriptions = subscriptions.OrderByDescending(s => s.StartDate);
        break;*@




    @*@foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EnrollmentDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }*@

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))